const songs = [
    { id: 2, title: 'Fur Elise', artist: 'Ludwig van Beethoven', genre: 'Classical', cover: 'fur-elise.jpg', audio: 'fur-elise.mp3' },
    { id: 3, title: 'Nocturne Op. 9 No. 2', artist: 'Frédéric Chopin', genre: 'Classical', cover: 'nocturne-op-9-no-2.jpg', audio: 'nocturne-op-9-no-2.mp3' },
    { id: 4, title: 'Canon in D', artist: 'Johann Pachelbel', genre: 'Classical', cover: 'canon-in-d.jpg', audio: 'canon-in-d.mp3' },
    { id: 5, title: 'The Four Seasons - Spring', artist: 'Antonio Vivaldi', genre: 'Classical', cover: 'four-seasons-spring.jpg', audio: 'four-seasons-spring.mp3' },
    { id: 53, title: 'Clair de Lune', artist: 'Claude Debussy', genre: 'Classical', cover: 'clair-de-lune.jpg', audio: 'clair-de-lune.mp3' },
    { id: 724, title: 'Moonlight Sonata', artist: 'Ludwig van Beethoven', genre: 'Classical', cover: 'moonlight-sonata.jpg', audio: 'moonlight-sonata.mp3' },
    { id: 12, title: 'Turkish March', artist: 'Wolfgang Amadeus Mozart', genre: 'Classical', cover: 'turkish-march.jpg', audio: 'turkish-march.mp3' },
    { id: 13, title: "Pirates of the Caribbean", artist: 'Klaus Badelt', genre: 'Soundtrack', cover: 'pirates-of-the-caribbean.jpg', audio: 'pirates-of-the-caribbean.mp3' },
    { id: 14, title: 'Symphony No. 9', artist: 'Ludwig van Beethoven', genre: 'Classical', cover: 'song.jpg', audio: 'symphony-no-9.mp3' },
    { id: 15, title: 'Eine Kleine Nachtmusik', artist: 'Wolfgang Amadeus Mozart', genre: 'Classical', cover: 'song.jpg', audio: 'eine-kleine-nachtmusik.mp3' },
    { id: 16, title: 'Symphony No. 40', artist: 'Wolfgang Amadeus Mozart', genre: 'Classical', cover: 'song.jpg', audio: 'symphony-no-40.mp3' },
    { id: 17, title: 'Minuet in G Major', artist: 'Johann Sebastian Bach', genre: 'Classical', cover: 'song.jpg', audio: 'minuet-in-g-major.mp3' },
    { id: 18, title: 'River Flows in You', artist: 'Yiruma', genre: 'New Age', cover: 'river-flows-in-you.jpg', audio: 'river-flows-in-you.mp3' },
    { id: 19, title: 'Kiss the Rain', artist: 'Yiruma', genre: 'New Age', cover: 'kiss-the-rain.jpg', audio: 'kiss-the-rain.mp3' },
    { id: 20, title: 'Spring Time', artist: 'Yiruma', genre: 'New Age', cover: 'spring-time.jpg', audio: 'spring-time.mp3' },
    { id: 21, title: 'Maybe', artist: 'Yiruma', genre: 'New Age', cover: 'maybe.jpg', audio: 'maybe.mp3' },
    { "id": 22, "title": "DDU-DU DDU-DU", "artist": "BLACKPINK", "genre": "K-Pop", "cover": "ddu-du-ddu-du.jpg", "audio": "ddu-du-ddu-du.mp3" },
    { "id": 23, "title": "Kill This Love", "artist": "BLACKPINK", "genre": "K-Pop", "cover": "kill-this-love.jpg", "audio": "kill-this-love.mp3" },
    { "id": 24, "title": "How You Like That", "artist": "BLACKPINK", "genre": "K-Pop", "cover": "how-you-like-that.jpg", "audio": "how-you-like-that.mp3" },
    { "id": 25, "title": "Pink Venom", "artist": "BLACKPINK", "genre": "K-Pop", "cover": "pink-venom.jpg", "audio": "pink-venom.mp3" },
    { "id": 26, "title": "Flowers", "artist": "BLACKPINK - Jisoo", "genre": "K-Pop", "cover": "flowers.jpg", "audio": "flowers.mp3" },
    { "id": 27, "title": "Lovesick Girls", "artist": "BLACKPINK", "genre": "K-Pop", "cover": "lovesick-girls.jpg", "audio": "lovesick-girls.mp3" },
    { "id": 28, "title": "Forever Young", "artist": "BLACKPINK", "genre": "K-Pop", "cover": "forever-young.jpg", "audio": "forever-young.mp3" },
    { "id": 29, "title": "Boombayah", "artist": "BLACKPINK", "genre": "K-Pop", "cover": "boombayah.jpg", "audio": "boombayah.mp3" },
    { "id": 30, "title": "Love Story", "artist": "Taylor Swift", "genre": "Country/Pop", "cover": "love-story.jpg", "audio": "love-story.mp3" },
    { "id": 31, "title": "You Belong With Me", "artist": "Taylor Swift", "genre": "Country/Pop", "cover": "you-belong-with-me.jpg", "audio": "you-belong-with-me.mp3" },
    { "id": 32, "title": "Shake It Off", "artist": "Taylor Swift", "genre": "Pop", "cover": "shake-it-off.jpg", "audio": "shake-it-off.mp3" },
    { "id": 33, "title": "Teardrops on My Guitar", "artist": "Taylor Swift", "genre": "Country", "cover": "teardrops-on-my-guitar.jpg", "audio": "teardrops-on-my-guitar.mp3" },
    { "id": 34, "title": "Cruel Summer", "artist": "Taylor Swift", "genre": "Pop", "cover": "cruel-summer.jpg", "audio": "cruel-summer.mp3" },
    { "id": 35, "title": "Fortnight", "artist": "Taylor Swift", "genre": "Alternative", "cover": "fortnight.jpg", "audio": "fortnight.mp3" },
    { "id": 36, "title": "Style", "artist": "Taylor Swift", "genre": "Pop", "cover": "style.jpg", "audio": "style.mp3" },
    { "id": 37, "title": "ME!", "artist": "Taylor Swift, Brendon Urie", "genre": "Pop", "cover": "me.jpg", "audio": "me.mp3" },
];

export default songs;